### ISSUE TITLE
サインアウト実装

### ISSUE THREAD

**Issue by kikudesuyo** [kikudesuyo/pratan#35]

**Comment by kikudesuyo** [comment]
@eteRnaL198 
サインアウト時にzustandのUserIdをクリアしないといけないんだけど、
ここにclearIdみたいな感じで追加していい?
```TypeScript
const useUserStore = create<UserState>((set) => ({
  userId: null,
  setUserId: (userId) => set({ userId }),
}));

export default useUserStore;

```
あと、サインアウトするときは、firebase用のキャッシュにも残っちゃうから、zustandとfirebaseの2つを削除するって感じなのかな?

**Comment by eteRnaL198** [comment]
んーー 俺もベストプラクティス理解できてないから、誰かがやってるの参考にした方がいいかも
クリア追加するか、setUserId使ってnullをセットするか かな

firebaseとZustandから削除はその通りで良いと思う👍

**Comment by kikudesuyo** [comment]
了解です!
